AWSTemplateFormatVersion: 2010-09-09

Description: Cloudcraft IAM role and policy for the architecture review

Parameters:
  CloudcraftExternalID:
    Type: String
    Default: badf895d-4c55-47db-81ba-cf6d9e16f97f

Resources:

  CloudcraftRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: cloudcraft_role_cf
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::968898580625:root
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref CloudcraftExternalID
      Policies:
        - PolicyName: cloudcraft_role_policy_cf
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: "Allow"
                Action:
                  - application-autoscaling:DescribeScalableTargets
                  - application-autoscaling:DescribeScalingPolicies
                  - autoscaling:DescribeAccountLimits
                  - autoscaling:DescribeAdjustmentTypes
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:DescribeAutoScalingInstances
                  - autoscaling:DescribeAutoScalingNotificationTypes
                  - autoscaling:DescribeLaunchConfigurations
                  - autoscaling:DescribeLifecycleHooks
                  - autoscaling:DescribeLifecycleHookTypes
                  - autoscaling:DescribeLoadBalancers
                  - autoscaling:DescribeLoadBalancerTargetGroups
                  - autoscaling:DescribeMetricCollectionTypes
                  - autoscaling:DescribeNotificationConfigurations
                  - autoscaling:DescribePolicies
                  - autoscaling:DescribeScalingProcessTypes
                  - autoscaling:DescribeScheduledActions
                  - autoscaling:DescribeTags
                  - autoscaling:DescribeTerminationPolicyTypes
                  - apigateway:GET
                  - cloudfront:GetCloudFrontOriginAccessIdentity
                  - cloudfront:GetDistribution
                  - cloudfront:ListCloudFrontOriginAccessIdentities
                  - cloudfront:ListDistributions
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:DescribeAlarmsForMetric
                  - cloudwatch:ListDashboards
                  - cloudwatch:ListMetrics
                  - dynamodb:DescribeLimits
                  - dynamodb:DescribeReservedCapacity
                  - dynamodb:DescribeReservedCapacityOfferings
                  - dynamodb:DescribeStream
                  - dynamodb:DescribeTable
                  - dynamodb:ListStreams
                  - dynamodb:ListTables
                  - dynamodb:ListTagsOfResource
                  - ec2-reports:ViewReservedInstanceUtilizationReport
                  - ec2-reports:ViewInstanceUsageReport
                  - ec2:DescribeAccountAttributes
                  - ec2:DescribeAddresses
                  - ec2:DescribeAvailabilityZones
                  - ec2:DescribeBundleTasks
                  - ec2:DescribeClassicLinkInstances
                  - ec2:DescribeConversionTasks
                  - ec2:DescribeCustomerGateways
                  - ec2:DescribeDhcpOptions
                  - ec2:DescribeExportTasks
                  - ec2:DescribeHosts
                  - ec2:DescribeIdentityIdFormat
                  - ec2:DescribeIdFormat
                  - ec2:DescribeImageAttribute
                  - ec2:DescribeImages
                  - ec2:DescribeImportImageTasks
                  - ec2:DescribeImportSnapshotTasks
                  - ec2:DescribeInstanceAttribute
                  - ec2:DescribeInstances
                  - ec2:DescribeInstanceStatus
                  - ec2:DescribeInternetGateways
                  - ec2:DescribeFlowLogs
                  - ec2:DescribeKeyPairs
                  - ec2:DescribeMovingAddresses
                  - ec2:DescribeNatGateways
                  - ec2:DescribeNetworkAcls
                  - ec2:DescribeNetworkInterfaceAttribute
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribePlacementGroups
                  - ec2:DescribePrefixLists
                  - ec2:DescribeRegions
                  - ec2:DescribeReservedInstances
                  - ec2:DescribeReservedInstancesListings
                  - ec2:DescribeReservedInstancesModifications
                  - ec2:DescribeReservedInstancesOfferings
                  - ec2:DescribeRouteTables
                  - ec2:DescribeScheduledInstanceAvailability
                  - ec2:DescribeScheduledInstances
                  - ec2:DescribeSecurityGroupReferences
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeStaleSecurityGroups
                  - ec2:DescribeSnapshotAttribute
                  - ec2:DescribeSnapshots
                  - ec2:DescribeSpotDatafeedSubscription
                  - ec2:DescribeSpotFleetInstances
                  - ec2:DescribeSpotFleetRequestHistory
                  - ec2:DescribeSpotFleetRequests
                  - ec2:DescribeSpotInstanceRequests
                  - ec2:DescribeSpotPriceHistory
                  - ec2:DescribeSubnets
                  - ec2:DescribeTags
                  - ec2:DescribeVolumeAttribute
                  - ec2:DescribeVolumes
                  - ec2:DescribeVolumeStatus
                  - ec2:DescribeVpcAttribute
                  - ec2:DescribeVpcClassicLink
                  - ec2:DescribeVpcClassicLinkDnsSupport
                  - ec2:DescribeVpcEndpoints
                  - ec2:DescribeVpcEndpointServices
                  - ec2:DescribeVpcPeeringConnections
                  - ec2:DescribeVpcs
                  - ec2:DescribeVpnConnections
                  - ec2:DescribeVpnGateways
                  - elasticache:DescribeCacheClusters
                  - elasticache:DescribeCacheEngineVersions
                  - elasticache:DescribeCacheParameterGroups
                  - elasticache:DescribeCacheParameters
                  - elasticache:DescribeCacheSecurityGroups
                  - elasticache:DescribeCacheSubnetGroups
                  - elasticache:DescribeEngineDefaultParameters
                  - elasticache:DescribeReplicationGroups
                  - elasticache:DescribeReservedCacheNodes
                  - elasticache:DescribeReservedCacheNodesOfferings
                  - elasticache:DescribeSnapshots
                  - elasticache:ListAllowedNodeTypeModifications
                  - elasticache:ListTagsForResource
                  - elasticfilesystem:DescribeTags
                  - elasticfilesystem:DescribeMountTargetSecurityGroups
                  - elasticfilesystem:DescribeFileSystems
                  - elasticfilesystem:DescribeMountTargets
                  - elasticloadbalancing:DescribeListeners
                  - elasticloadbalancing:DescribeLoadBalancerAttributes
                  - elasticloadbalancing:DescribeLoadBalancerAttributes
                  - elasticloadbalancing:DescribeLoadBalancerPolicyTypes
                  - elasticloadbalancing:DescribeLoadBalancerPolicies
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeRules
                  - elasticloadbalancing:DescribeSSLPolicies
                  - elasticloadbalancing:DescribeTags
                  - elasticloadbalancing:DescribeTags
                  - elasticloadbalancing:DescribeTargetGroupAttributes
                  - elasticloadbalancing:DescribeTargetGroups
                  - elasticloadbalancing:DescribeTargetHealth
                  - es:DescribeElasticsearchDomain
                  - es:DescribeElasticsearchDomains
                  - es:DescribeElasticsearchDomainConfig
                  - es:ListDomainNames
                  - es:ListTags
                  - kinesis:DescribeLimits
                  - kinesis:DescribeStream
                  - kinesis:DescribeStreamSummary
                  - kinesis:ListStreams
                  - kinesis:ListTagsForStream
                  - lambda:GetPolicy
                  - lambda:ListAliases
                  - lambda:ListEventSourceMappings
                  - lambda:ListFunctions
                  - lambda:ListVersionsByFunction
                  - rds:DescribeAccountAttributes
                  - rds:DescribeDBClusterParameterGroups
                  - rds:DescribeDBClusterParameters
                  - rds:DescribeDBClusters
                  - rds:DescribeDBClusterSnapshotAttributes
                  - rds:DescribeDBEngineVersions
                  - rds:DescribeDBInstances
                  - rds:DescribeDBParameterGroups
                  - rds:DescribeDBParameters
                  - rds:DescribeDBSecurityGroups
                  - rds:DescribeDBSnapshotAttributes
                  - rds:DescribeDBSnapshots
                  - rds:DescribeDBSnapshots
                  - rds:DescribeDBSubnetGroups
                  - rds:DescribeEngineDefaultClusterParameters
                  - rds:DescribeEngineDefaultParameters
                  - rds:DescribeEventCategories
                  - rds:DescribeEventSubscriptions
                  - rds:DescribeOptionGroupOptions
                  - rds:DescribeOptionGroups
                  - rds:DescribeOrderableDBInstanceOptions
                  - rds:DescribePendingMaintenanceActions
                  - rds:DescribeReservedDBInstances
                  - rds:DescribeReservedDBInstancesOfferings
                  - rds:ListTagsForResource
                  - redshift:DescribeClusterParameterGroups
                  - redshift:DescribeClusterParameters
                  - redshift:DescribeClusterSecurityGroups
                  - redshift:DescribeClusterSnapshots
                  - redshift:DescribeClusterSubnetGroups
                  - redshift:DescribeClusterVersions
                  - redshift:DescribeClusters
                  - redshift:DescribeDefaultClusterParameters
                  - redshift:DescribeEventCategories
                  - redshift:DescribeEventSubscriptions
                  - redshift:DescribeEvents
                  - redshift:DescribeHsmClientCertificates
                  - redshift:DescribeHsmConfigurations
                  - redshift:DescribeLoggingStatus
                  - redshift:DescribeOrderableClusterOptions
                  - redshift:DescribeReservedNodeOfferings
                  - redshift:DescribeReservedNodes
                  - redshift:DescribeResize
                  - redshift:DescribeSnapshotCopyGrants
                  - redshift:DescribeTableRestoreStatus
                  - redshift:DescribeTags
                  - route53:GetHostedZone
                  - route53:GetHostedZoneCount
                  - route53:ListGeoLocations
                  - route53:ListHealthChecks
                  - route53:ListHostedZones
                  - route53:ListHostedZonesByName
                  - route53:ListQueryLoggingConfigs
                  - route53:ListResourceRecordSets
                  - route53:ListReusableDelegationSets
                  - route53:ListTagsForResource
                  - route53:ListTagsForResources
                  - route53:ListTrafficPolicies
                  - route53:ListTrafficPolicyInstances
                  - route53:ListTrafficPolicyInstancesByHostedZone
                  - route53:ListTrafficPolicyInstancesByPolicy
                  - route53:ListTrafficPolicyVersions
                  - route53domains:GetDomainDetail
                  - route53domains:GetDomainSuggestions
                  - route53domains:ListDomains
                  - route53domains:ListOperations
                  - route53domains:ListTagsForDomain
                  - s3:ListAllMyBuckets
                  - s3:ListBucket
                  - s3:ListBucketVersions
                  - sns:GetSubscriptionAttributes
                  - sns:GetTopicAttributes
                  - sns:ListEndpointsByPlatformApplication
                  - sns:ListPlatformApplications
                  - sns:ListSubscriptions
                  - sns:ListSubscriptionsByTopic
                  - sns:ListTopics
                  - sqs:GetQueueAttributes
                  - sqs:GetQueueUrl
                  - sqs:ListDeadLetterSourceQueues
                  - sqs:ListQueues
                Resource:
                  - "*"
